import "../styles/globals.css"
import { MainHeader } from "../components/Navigation"
import {font} from "../styles/font"

export const metadata = {
  title: 'Mi primera app en Next.js',
  description: 'Generated by Next.js',
}


export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      {/* <body className={font.variable}> */}
      <body className={font.className}>
        <MainHeader/>
        {children}
      </body>
    </html>
  )
}
