import "../styles/globals.css"
import { MainHeader } from "./components/Navigation"

export const metadata = {
  title: 'Mi primera app en Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body>
        <MainHeader/>
        {children}
      </body>
    </html>
  )
}
