import "../styles/globals.css"
import { MainHeader } from "./components/Navigation"
import {font} from "../styles/font"
import { LangProvider } from "./context/LangContext"

export const metadata = {
  title: 'Portfolio',
  description: 'Generated by Next.js',
  image: 'https://example.com/ogp.png',
}


export default function RootLayout({ children }) {
 return (
    <html>
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description}/>
        <link rel="icon" type="image/x-icon" href="../public/next.svg"/>
        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'></link>
        <link rel="stylesheet" href="../styles/globals.css" ></link>
      </head>
      {/* <body className={font.variable}> */}
      <body className={font.className}>
        <LangProvider>
            <MainHeader/>
            {children}
        </LangProvider>
      </body>
    </html>
  )
}
